spring:
    application:
        name: schedmailer
    datasource:
        url: ${DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/schedmailer}
        username: ${DATA_SOURCE_USERNAME:postgres}
        password: ${DATA_SOURCE_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: classpath:db/changelog/changelog-master.yaml
server:
    error:
        include-message: always
    port: ${BASE_PORT:8080}
encryption:
    key: ${ENCRYPTION_KEY:9S4wqeHxDbHaG83Fj6Kr2Q==}
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /api-docs/swagger-ui.html
