spring:
    application:
        name: schedmailer
    datasource:
        url: jdbc:postgresql://${DB_ADDRESS:localhost}:${DB_PORT:5432}/${DB_DATABASE:schedmailer}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: classpath:db/changelog/changelog-master.yaml
server:
    error:
        include-message: always
    port: ${BASE_PORT:8080}
encryption:
    key: ${ENCRYPTION_KEY:9S4wqeHxDbHaG83Fj6Kr2Q==}
